settings:
  title: 'Status Page'
  url: 'https://status.linliu.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www # unique identifier
    name: The www
    description: 'www' # default=empty
    url: 'https://www.linliu.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: status
    name: The status
    description: 'status'
    url: 'https://status.linliu.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog
    name: The Blog
    url: 'https://blog.linliu.xyz/'
    method: GET
    expectStatus: 200
